## 네이버 금융 뉴스기사 수집
* [삼성전자 : 네이버 금융](https://finance.naver.com/item/news.naver?code=005930)

```
<html lang="ko">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=euc-kr">
<title>네이버 금융</title>

<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20220511192542/css/newstock.css">
<style data-emotion="css" data-s=""></style>
</head>


<body>
<script type="text/javascript" src="https://ssl.pstatic.net/imgstock/static.pc/20220511192542/js/jindo.min.ns.1.5.3.euckr.js"></script>
		<div class="tb_cont">
			<div class="tlline2">
				<strong><span class="red03">종목</span>뉴스</strong>
				<!-- [D] 선택시 blind 태그 추가 -->
				<div class="info_txt">종목뉴스 안내<a href="#" onclick="togglePannel('layer_section'); clickcr(this,'stn.ninfo','','',event); return false;" class="btn_info_layer"><img src="https://ssl.pstatic.net/static/nfinance/2017/10/13/btn_help2.png" alt="상세 설명"></a>
					<div class="layer_section" id="layer_section" style="display:none">
						<strong>네이버 증권 종목뉴스 안내</strong>
						<p class="txt">
							AI(인공지능 검색기술)을 이용한 종목 관련 뉴스입니다. <br>관련뉴스는 자동으로 묶어 보여줍니다.
							<br>
							<span class="txt_opt">
								검색영역 옵션
								<br>
								제목 : 제목에서 종목명이 검색된 결과입니다. <br>
								내용 : 제목과 본문에서 종목명이 검색된 결과입니다.
							</span>
						</p>
						<a href="#" onclick="togglePannel('layer_section'); return false;" class="btn_close"><span class="blind">닫기</span></a>
					</div>
				</div>
			</div>
			
			<table summary="종목뉴스의 제목, 정보제공, 날짜" cellspacing="0" class="type5">
				<caption>종목뉴스</caption>
				<colgroup>
					<col>
					<col width="130px">
					<col width="110px">
				</colgroup>
				<thead>
					<tr>
						<th scope="col">제목</th>
						<th scope="col">정보제공</th>
						<th scope="col">날짜</th>
					</tr>
				</thead>

		 		<tbody>
 							
 							<tr class="first">	 						
	 							<td class="title">
									<a href="/item/news_read.naver?article_id=0004836222&amp;office_id=014&amp;code=005930&amp;page=1&amp;sm=title_entity_id.basic" class="tit" onclick="clickcr(this,'stn.ntitclust','','',event);" target="_top">삼성, 포켓몬 이어 뚱랑이 갤Z플립3에 입힌다</a>
									
								</td>
								<td class="info">파이낸셜뉴스</td>
								<td class="date"> 2022.05.15 11:52</td>
 							</tr>	 					
 						

 							<tr>	 						
	 							<td class="title">
									<a href="/item/news_read.naver?article_id=0001990771&amp;office_id=016&amp;code=005930&amp;page=1&amp;sm=title_entity_id.basic" class="tit" onclick="clickcr(this,'stn.ntitclust','','',event);" target="_top">삼성전자, 16일부터 갤럭시 Z 플립3 '무직타이거 에디션' 한정 판매</a>
									
								</td>
								<td class="info">헤럴드경제</td>
								<td class="date"> 2022.05.15 11:41</td>
 							</tr>	 					
 				
				</tbody>
			</table>
 						
			<!--- 종목뉴스 끝--->
			<!--- 페이지 네비게이션 시작--->
			
			<table summary="페이지 네비게이션 리스트" class="Nnavi" align="center">
				<caption>페이지 네비게이션</caption>
				<tbody><tr>
					
						
		                
		                <td class="on">
				<a href="/item/news_news.nhn?code=005930&amp;page=1&amp;sm=title_entity_id.basic&amp;clusterId=" onclick="clickcr(this,'stn.npag','','',event);">1</a>
				</td>
                <td>
				<a href="/item/news_news.nhn?code=005930&amp;page=2&amp;sm=title_entity_id.basic&amp;clusterId=" onclick="clickcr(this,'stn.npag','','',event);">2</a>
				</td>
		                <td class="pgR">
				<a href="/item/news_news.nhn?code=005930&amp;page=11&amp;sm=title_entity_id.basic&amp;clusterId=" onclick="clickcr(this,'stn.npag','','',event);">
				다음<img src="https://ssl.pstatic.net/static/n/cmn/bu_pgarR.gif" width="3" height="5" alt="" border="0">
				</a>
				</td>

		                <td class="pgRR">
				<a href="/item/news_news.nhn?code=005930&amp;page=1269&amp;sm=title_entity_id.basic&amp;clusterId=" onclick="clickcr(this,'stn.npag','','',event);">맨뒤
				<img src="https://ssl.pstatic.net/static/n/cmn/bu_pgarRR.gif" width="8" height="5" alt="" border="0">
				</a>
				</td>
		            
				</tr>
			</tbody></table>
            

	<script type="text/javascript" src="https://ssl.pstatic.net/imgstock/static.pc/20220511192542/js/lcslog.js"></script>
</div>
</body>
</html>
```

## pandas만으로 데이터 수집하기

In [1]:
# pandas 불러오기
import pandas as pd

## 검색 값 설정하기
* 웹사이트에서 검색한 URL 안에 우리의 검색어가 들어가 있습니다.
* 이렇게 검색어를 URL에 붙여서 넘기는 문구를 쿼리스트링이라고 부릅니다.
* 이 문자열을 검색어에 맞게 변경해 줍니다.
* 쿼리스트링 : 쿼리 문자열은 지정된 매개변수에 값을 할당하는 Uniform Resource Locator의 일부입니다. 쿼리 문자열에는 일반적으로 웹 브라우저나 기타 클라이언트 응용 프로그램에서 기본 URL에 추가한 필드가 포함됩니다.

<img src="https://media.vlpt.us/images/keywookim/post/d23e05e7-0cfb-4347-ab89-f1b8a3d170c8/creating_query_strings1.png">

In [2]:
print("https://finance.naver.com/item/news_news.nhn?code=005930&page=1&sm=title_entity_id.basic&clusterId=")

https://finance.naver.com/item/news_news.nhn?code=005930&page=1&sm=title_entity_id.basic&clusterId=

In [3]:
# 수집할 url을 가져옵니다.
item_code = "005930"
item_name = "삼성전자"
page_no = 1

In [6]:
# url
url = f"https://finance.naver.com/item/news_news.nhn?code={item_code}&page={page_no}&sm=title_entity_id.basic&clusterId="
print(url)

https://finance.naver.com/item/news_news.nhn?code=005930&page=1&sm=title_entity_id.basic&clusterId=

## read_html 로 수집하기
* 네이버 금융의 주가 기사를 read_html로 수집해서 table 이라는 변수에 담습니다.

In [8]:
# 수집결과 는 table이라는 변수에 담아주세요.
# table
table = pd.read_html(url, encoding='cp949')

In [13]:
len(table)

6

In [18]:
table[0].iloc[:4,:]

,제목,정보제공,날짜
0,"""美ETF산업·中메타버스 투자""…삼성운용 ETF 2종 상장",이데일리,2022.05.17 09:21
1,"연관기사 목록 삼성운용, 세계최초 '中메타버스' 투자 ETF 등 2종 상장 파이낸...","연관기사 목록 삼성운용, 세계최초 '中메타버스' 투자 ETF 등 2종 상장 파이낸...","연관기사 목록 삼성운용, 세계최초 '中메타버스' 투자 ETF 등 2종 상장 파이낸..."
2,"삼성운용, 세계최초 '中메타버스' 투자 ETF 등 2종 상장",파이낸셜뉴스,2022.05.17 09:20
3,"삼성자산운용, 미국ETF산업·중국 메타버스 산업 관련 ETF 신규상장",헤럴드경제,2022.05.17 08:58

## 데이터프레임으로 만들기
* 위에서 수집한 결과 중 table 변수 안에 있는 0번째 인덱스 값을 가져와서 df 라는 변수에 담아주세요.

In [20]:
# table의 0번째 인덱스 값을 df 라는 변수에 담습니다.
# df
df = pd.DataFrame(table[0])
print(df.shape)
df.head()

(21, 3)

,제목,정보제공,날짜
0,"""美ETF산업·中메타버스 투자""…삼성운용 ETF 2종 상장",이데일리,2022.05.17 09:21
1,"연관기사 목록 삼성운용, 세계최초 '中메타버스' 투자 ETF 등 2종 상장 파이낸...","연관기사 목록 삼성운용, 세계최초 '中메타버스' 투자 ETF 등 2종 상장 파이낸...","연관기사 목록 삼성운용, 세계최초 '中메타버스' 투자 ETF 등 2종 상장 파이낸..."
2,"삼성운용, 세계최초 '中메타버스' 투자 ETF 등 2종 상장",파이낸셜뉴스,2022.05.17 09:20
3,"삼성자산운용, 미국ETF산업·중국 메타버스 산업 관련 ETF 신규상장",헤럴드경제,2022.05.17 08:58
4,삼성전자 반도체 핵심기술 中에 넘겨…800억 부당이득,한국경제,2022.05.17 09:20

## 반복문으로 데이터 모두 가져오기
* for 문을 사용해 table 이라는 변수 안에 있는 값을 모두 가져오기
* temp_list 에 수집한 값을 담아주세요.

In [29]:
# temp_list = []
# for news in table:
temp_list = []
cols = df.columns
for news in table[:-1]:
    news.columns=cols
    temp_list.append(news)
len(temp_list)

5

## 수집한 데이터 하나의 데이터프레임으로 합치기

<img src="https://pandas.pydata.org/docs/_images/merging_concat_basic.png">

* [Merge, join, concatenate and compare documentation](https://pandas.pydata.org/docs/user_guide/merging.html#merge-join-concatenate-and-compare)

* concat :  
    * axis=0 행을 기준으로 위아래로 같은 컬럼끼리 값을 이어 붙여 새로운 행을 만듦
    * axis=1 컬럼을 기준으로 인덱스가 같은 값을 옆으로 붙여 새로운 컬럼을 만듦

In [42]:
# pd.concat
df_temp = pd.concat(temp_list)
df_temp.reset_index(inplace=True, drop=True)
print(df_temp.shape)
df_temp.head()

(28, 3)

,제목,정보제공,날짜
0,"""美ETF산업·中메타버스 투자""…삼성운용 ETF 2종 상장",이데일리,2022.05.17 09:21
1,"연관기사 목록 삼성운용, 세계최초 '中메타버스' 투자 ETF 등 2종 상장 파이낸...","연관기사 목록 삼성운용, 세계최초 '中메타버스' 투자 ETF 등 2종 상장 파이낸...","연관기사 목록 삼성운용, 세계최초 '中메타버스' 투자 ETF 등 2종 상장 파이낸..."
2,"삼성운용, 세계최초 '中메타버스' 투자 ETF 등 2종 상장",파이낸셜뉴스,2022.05.17 09:20
3,"삼성자산운용, 미국ETF산업·중국 메타버스 산업 관련 ETF 신규상장",헤럴드경제,2022.05.17 08:58
4,삼성전자 반도체 핵심기술 中에 넘겨…800억 부당이득,한국경제,2022.05.17 09:20

## 위에서 수집한 데이터에서 결측치를 제거합니다.

In [40]:
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   28 non-null     int64
 1   제목      28 non-null     object
 2   정보제공    28 non-null     object
 3   날짜      28 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.0+ KB

In [44]:
# dropna
df_temp.dropna(how='any', axis=1).dropna(how='all',axis=1)
df_temp

,제목,정보제공,날짜
0,"""美ETF산업·中메타버스 투자""…삼성운용 ETF 2종 상장",이데일리,2022.05.17 09:21
1,"연관기사 목록 삼성운용, 세계최초 '中메타버스' 투자 ETF 등 2종 상장 파이낸...","연관기사 목록 삼성운용, 세계최초 '中메타버스' 투자 ETF 등 2종 상장 파이낸...","연관기사 목록 삼성운용, 세계최초 '中메타버스' 투자 ETF 등 2종 상장 파이낸..."
2,"삼성운용, 세계최초 '中메타버스' 투자 ETF 등 2종 상장",파이낸셜뉴스,2022.05.17 09:20
3,"삼성자산운용, 미국ETF산업·중국 메타버스 산업 관련 ETF 신규상장",헤럴드경제,2022.05.17 08:58
4,삼성전자 반도체 핵심기술 中에 넘겨…800억 부당이득,한국경제,2022.05.17 09:20
5,"코스피, 기관 매수에 상승 출발…삼성전자 6.7만원 회복",한국경제,2022.05.17 09:17
6,삼성전자 에어컨 생산라인 풀가동 중…'무풍에어컨 갤러리 효과',아시아경제,2022.05.17 09:07
7,여름 대목에 대비…삼성전자 2월부터 에어컨 공장 ‘풀가동’,헤럴드경제,2022.05.17 08:58
8,연관기사 목록 비스포크 무풍 갤러리 인기…삼성 에어컨 생산라인 풀가동 머니투데이...,연관기사 목록 비스포크 무풍 갤러리 인기…삼성 에어컨 생산라인 풀가동 머니투데이...,연관기사 목록 비스포크 무풍 갤러리 인기…삼성 에어컨 생산라인 풀가동 머니투데이...
9,비스포크 무풍 갤러리 인기…삼성 에어컨 생산라인 풀가동,머니투데이,2022.05.17 08:43
10,"[1일IT템]삼성전자 ""로블록스에서 팝스타의 꿈 도전하세요""",파이낸셜뉴스,2022.05.17 08:51
11,"포브스 ""삼성, 세계 기술기업 2위→4위...공급망 발목""",머니투데이,2022.05.17 08:12
12,TSMC보다 한 발 빨랐다…삼성이 꺼낸 '비장의 무기',한국경제,2022.05.16 21:02
13,삼성전자 5대 매출처에 퀄컴 첫 등장,매일경제,2022.05.16 19:55
14,"연관기사 목록 삼성전자, 1분기 5대 매출처에 퀄컴 첫 포함 아시아경제 202...","연관기사 목록 삼성전자, 1분기 5대 매출처에 퀄컴 첫 포함 아시아경제 202...","연관기사 목록 삼성전자, 1분기 5대 매출처에 퀄컴 첫 포함 아시아경제 202..."
15,"삼성전자, 1분기 5대 매출처에 퀄컴 첫 포함",아시아경제,2022.05.16 18:43
16,"퀄컴, 삼성전자 5대 매출처에 첫 포함",서울경제,2022.05.16 18:07
17,"DB, 삼성전자 출신 설계 전문가 영입..""팹리스 경쟁력 강화""",이데일리,2022.05.16 18:46
18,"연관기사 목록 DB하이텍 ""팹리스 경쟁력 강화""... 삼성전자 출신 설계 전문가 ...","연관기사 목록 DB하이텍 ""팹리스 경쟁력 강화""... 삼성전자 출신 설계 전문가 ...","연관기사 목록 DB하이텍 ""팹리스 경쟁력 강화""... 삼성전자 출신 설계 전문가 ..."
19,"DB하이텍 ""팹리스 경쟁력 강화""... 삼성전자 출신 설계 전문가 영...",파이낸셜뉴스,2022.05.16 18:01
20,팹리스 키우는 DB하이텍…삼성전자 출신 설계전문가 영입,파이낸셜뉴스,2022.05.16 15:44
21,"삼성운용, 세계최초 '中메타버스' 투자 ETF 등 2종 상장",파이낸셜뉴스,2022.05.17 09:20
22,"삼성자산운용, 미국ETF산업·중국 메타버스 산업 관련 ETF 신규상장",헤럴드경제,2022.05.17 08:58
23,비스포크 무풍 갤러리 인기…삼성 에어컨 생산라인 풀가동,머니투데이,2022.05.17 08:43
24,"삼성전자, 1분기 5대 매출처에 퀄컴 첫 포함",아시아경제,2022.05.16 18:43
25,"퀄컴, 삼성전자 5대 매출처에 첫 포함",서울경제,2022.05.16 18:07
26,"DB하이텍 ""팹리스 경쟁력 강화""... 삼성전자 출신 설계 전문가 영...",파이낸셜뉴스,2022.05.16 18:01
27,팹리스 키우는 DB하이텍…삼성전자 출신 설계전문가 영입,파이낸셜뉴스,2022.05.16 15:44

## 네이버 수집한 기사에서 "제목"에 "연관기사"가 들어가는 데이터를 제거합니다.

* <font color="red">.str.contains 를 사용하며 조건의 반대에는 앞에 ~ 표시로 표현할 수 있습니다.</red>

In [61]:
df = df_temp[~df_temp['제목'].str.contains('연관기사')]
df.reset_index(inplace=True, drop=True)
print(df.shape)
df

(24, 3)

                                           제목    정보제공                날짜
0            "美ETF산업·中메타버스 투자"…삼성운용 ETF 2종 상장    이데일리  2022.05.17 09:21
1           삼성운용, 세계최초 '中메타버스' 투자 ETF 등 2종 상장  파이낸셜뉴스  2022.05.17 09:20
2      삼성자산운용, 미국ETF산업·중국 메타버스 산업 관련 ETF 신규상장   헤럴드경제  2022.05.17 08:58
3               삼성전자 반도체 핵심기술 中에 넘겨…800억 부당이득    한국경제  2022.05.17 09:20
4             코스피, 기관 매수에 상승 출발…삼성전자 6.7만원 회복    한국경제  2022.05.17 09:17
5          삼성전자 에어컨 생산라인 풀가동 중…'무풍에어컨 갤러리 효과'   아시아경제  2022.05.17 09:07
6            여름 대목에 대비…삼성전자 2월부터 에어컨 공장 ‘풀가동’   헤럴드경제  2022.05.17 08:58
7              비스포크 무풍 갤러리 인기…삼성 에어컨 생산라인 풀가동   머니투데이  2022.05.17 08:43
8           [1일IT템]삼성전자 "로블록스에서 팝스타의 꿈 도전하세요"  파이낸셜뉴스  2022.05.17 08:51
9            포브스 "삼성, 세계 기술기업 2위→4위...공급망 발목"   머니투데이  2022.05.17 08:12
10             TSMC보다 한 발 빨랐다…삼성이 꺼낸 '비장의 무기'    한국경제  2022.05.16 21:02
11                       삼성전자 5대 매출처에 퀄컴 첫 등장    매일경제  2022.05.16 19:55
12                  삼성전자, 1분기 5대 매출처에 퀄컴 첫 포함   아시아경제  2022.05.16 18:43
13                      퀄컴, 삼성전자 5대 매출처에 첫 포함    서울경제  2022.05.16 18:07
14        DB, 삼성전자 출신 설계 전문가 영입.."팹리스 경쟁력 강화"    이데일리  2022.05.16 18:46
15  DB하이텍 "팹리스 경쟁력 강화"... 삼성전자 출신 설계 전문가 영...  파이낸셜뉴스  2022.05.16 18:01
16             팹리스 키우는 DB하이텍…삼성전자 출신 설계전문가 영입  파이낸셜뉴스  2022.05.16 15:44
17          삼성운용, 세계최초 '中메타버스' 투자 ETF 등 2종 상장  파이낸셜뉴스  2022.05.17 09:20
18     삼성자산운용, 미국ETF산업·중국 메타버스 산업 관련 ETF 신규상장   헤럴드경제  2022.05.17 08:58
19             비스포크 무풍 갤러리 인기…삼성 에어컨 생산라인 풀가동   머니투데이  2022.05.17 08:43
20                  삼성전자, 1분기 5대 매출처에 퀄컴 첫 포함   아시아경제  2022.05.16 18:43
21                      퀄컴, 삼성전자 5대 매출처에 첫 포함    서울경제  2022.05.16 18:07
22  DB하이텍 "팹리스 경쟁력 강화"... 삼성전자 출신 설계 전문가 영...  파이낸셜뉴스  2022.05.16 18:01
23             팹리스 키우는 DB하이텍…삼성전자 출신 설계전문가 영입  파이낸셜뉴스  2022.05.16 15:44

## 위의 과정을 함수로 만듭니다.
* 빈칸을 완성해 수집한 table 을 넘겨주면 데이터프레임을 반환하는 함수를 완성해 주세요.

In [65]:
# get_url item_code, page_no 를 넘기면 url 을 반환하는 함수
def get_url(item_code, page_no):
    url = f"https://finance.naver.com/item/news_news.nhn?code={item_code}&page={page_no}&sm=title_entity_id.basic&clusterId="
    return url

In [67]:
print(get_url(123,1))

https://finance.naver.com/item/news_news.nhn?code=123&page=1&sm=title_entity_id.basic&clusterId=

## 뉴스 한 페이지를 수집하는 함수
```
1) URL 을 받아옴
2) read_html 로 테이블 정보를 받아옴
3) 데이터프레임 컬럼명을 ["제목", "정보제공", "날짜"]로 변경
4) temp_list 에 데이터프레임을 추가
5) concat 으로 리스트 병합하여 하나의 데이터프레임으로 만들기
6) 결측치 제거
7) 연관기사 제거
8) 데이터프레임 반환
```

In [70]:
# get_one_page_news 함수 만들기
# get_url 에 item_code, page_no 를 넘겨 url 을 받아오고
# 뉴스 한 페이지를 수집하는 함수
def get_one_page_news(item_code, page_no):
# 1) URL 을 받아옴
    url = get_url(item_code, page_no)
    print('url :',url)

# 2) read_html 로 테이블 정보를 받아옴
    table = pd.read_html(url, encoding='cp949')

# 3) 데이터프레임 컬럼명을 ["제목", "정보제공", "날짜"]로 변경
# 4) temp_list 에 데이터프레임을 추가        
    temp_list = []
    std_col = table[0].columns
    for news in table[:-1]:
        news.columns = std_col
        temp_list.append(news)
    df_temp = pd.concat(temp_list)
    
# 5) concat 으로 리스트 병합하여 하나의 데이터프레임으로 만들기
    df_temp = pd.concat(temp_list)
    
# 6) 결측치 제거
    df_temp = df_temp.dropna(how='all', axis=0).dropna(how='all', axis=1)
    
# 7) 연관기사 제거
    df = df_temp[~df_temp['제목'].str.contains('연관기사')]
    df.reset_index(inplace=True, drop=True)

# 8) 데이터프레임 반환
    return df

* 아래 코드를 실행했을 때 수집된 데이터프레임이 출력된다면 잘 만들어진 것입니다.

In [71]:
item_code = "005930"
page_no = 2

temp = get_one_page_news(item_code, page_no)
temp

url : https://finance.naver.com/item/news_news.nhn?code=005930&page=2&sm=title_entity_id.basic&clusterId=

                                           제목    정보제공                날짜
0                삼성, 2022년형 창문형 에어컨 ‘윈도우핏’ 출시  파이낸셜뉴스  2022.05.16 18:01
1       설치 환경 따라 프레임 직접 선택…삼성 ‘창문형 에어컨’ 업그레이드   헤럴드경제  2022.05.16 11:26
2                삼성, 편의성 높인 창문형 에어컨 ‘윈도우핏’ 출시   헤럴드경제  2022.05.16 11:25
3           삼성전자, 창문형 에어컨 '윈도우핏' 출시…"어플로도 작동"    서울경제  2022.05.16 11:14
4            삼성전자, 1분기 투자만 7.9조…올해도 공격적 투자 계속   머니투데이  2022.05.16 17:55
5               "갤럭시도 애플 아이폰처럼…" 삼성전자, 사활 걸었다    한국경제  2022.05.16 17:33
6        삼성의 전용 칩 승부수…폰-PC-가전 묶는 '갤럭시 생태계' 구축    한국경제  2022.05.16 17:25
7            [줌인]삼성 비스포크 가전 빛낸 31세 가구·공간 디자이너    이데일리  2022.05.16 17:21
8        삼성·네이버·쿠팡 출신 개발인재 영입한 메쉬코리아 "부릉 고도화"   머니투데이  2022.05.16 17:12
9         수원 망포동에 푸르지오 두 단지 청약... “삼성이 배후 수요”    조선비즈  2022.05.16 15:01
10                        삼성전자, 사내 벤처 59개사 배출    서울경제  2022.05.16 11:38
11      삼성이 키운 반도체 전사 2000명…‘Y노믹스’로 인재풀 날개 달까   헤럴드경제  2022.05.16 11:14
12  ‘삼성공대’ 출신 2천명이나 되는데…“아직도 반도체 인력 턱없이 부족...   헤럴드경제  2022.05.16 10:31
13         올여름 폭염에 대세 된 이것…파세코 이어 삼성도 신제품 선보여    매일경제  2022.05.16 11:02
14        "좋은데 시끄럽다" 말 나오자 삼성 창문형 에어컨, 소음 잡았다   머니투데이  2022.05.16 11:00
15               삼성 잡으려고 칼 갈았네…일본, 또 6조 '돈폭탄'    한국경제  2022.05.16 11:02
16      설치 환경 따라 프레임 직접 선택…삼성 ‘창문형 에어컨’ 업그레이드   헤럴드경제  2022.05.16 11:26
17               삼성, 편의성 높인 창문형 에어컨 ‘윈도우핏’ 출시   헤럴드경제  2022.05.16 11:25
18          삼성전자, 창문형 에어컨 '윈도우핏' 출시…"어플로도 작동"    서울경제  2022.05.16 11:14
19       삼성의 전용 칩 승부수…폰-PC-가전 묶는 '갤럭시 생태계' 구축    한국경제  2022.05.16 17:25
20  ‘삼성공대’ 출신 2천명이나 되는데…“아직도 반도체 인력 턱없이 부족...   헤럴드경제  2022.05.16 10:31
21        "좋은데 시끄럽다" 말 나오자 삼성 창문형 에어컨, 소음 잡았다   머니투데이  2022.05.16 11:00

## 반복문을 사용해 10페이지까지 수집
* 위에서 만든 함수를 활용합니다.
* time.sleep() 을 통해 데이터를 쉬었다 가져옵니다.

In [93]:
import time
from tqdm import trange

page_no = 5
item_code = "005930"
news_list = []

for page in trange(1,page_no):
    temp = get_one_page_news(item_code, page)
    news_list.append(temp)
    time.sleep(0.2)

news_df = pd.concat(news_list)
news_df.reset_index(inplace=True, drop=True)
news_df

  0%|                                                                                            | 0/4 [00:00<?, ?it/s]

url : https://finance.naver.com/item/news_news.nhn?code=005930&page=1&sm=title_entity_id.basic&clusterId=

 25%|█████████████████████                                                               | 1/4 [00:00<00:01,  1.86it/s]

url : https://finance.naver.com/item/news_news.nhn?code=005930&page=2&sm=title_entity_id.basic&clusterId=

 50%|██████████████████████████████████████████                                          | 2/4 [00:01<00:01,  1.76it/s]

url : https://finance.naver.com/item/news_news.nhn?code=005930&page=3&sm=title_entity_id.basic&clusterId=

 75%|███████████████████████████████████████████████████████████████                     | 3/4 [00:01<00:00,  1.84it/s]

url : https://finance.naver.com/item/news_news.nhn?code=005930&page=4&sm=title_entity_id.basic&clusterId=

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.79it/s]

                                      제목    정보제공                날짜
0      기관 '사자'에 코스피·코스닥 동반 상승…삼성전자 1%대 ↑   아시아경제  2022.05.17 11:07
1   대기업 1분기 매출 800조 육박 '사상 최대'…삼성 압도적 1위    한국경제  2022.05.17 10:54
2              비스포크 인기에 에어컨 생산 풀가동 나선 삼성    매일경제  2022.05.17 10:44
3     비스포크 무풍에어컨 인기…삼성전자 생산라인 2월부터 ‘풀가동’    이데일리  2022.05.17 09:51
4     삼성전자 에어컨 생산라인 풀가동 중…'무풍에어컨 갤러리 효과'   아시아경제  2022.05.17 09:07
..                                   ...     ...               ...
85   삼성전자, 유럽 최대 디스플레이 전시회서 ‘최고의 신기술’ 선정    서울경제  2022.05.15 09:35
86      삼성전자의 '스마트 사이니지' 유럽 최대 전시회 사로잡았다   머니투데이  2022.05.15 09:26
87           삼성전자 제작 단편영화, 5년 만에 日 전국 개봉    서울경제  2022.05.15 14:59
88  유럽 홀린 삼성 스마트 사이니지…ISE 2022서 다수 부문 수상  이코노미스트  2022.05.15 16:01
89      삼성 스마트 사이니지, ISE2022서 최고의 기술력 과시   아시아경제  2022.05.15 10:43

[90 rows x 3 columns]

## 위에서 수집한 데이터는 news_list 라는 변수에 들어있습니다. 판다스를 활용해 하나의 데이터프레임으로 만들어 주세요.

* concat :  
    * axis=0 행을 기준으로 위아래로 같은 컬럼끼리 값을 이어 붙여 새로운 행을 만듦
    * axis=1 컬럼을 기준으로 인덱스가 같은 값을 옆으로 붙여 새로운 컬럼을 만듦

In [84]:
# df_news
df_news = pd.concat(news_list)
df_news.reset_index(inplace=True, drop=True)
df_news

                                      제목    정보제공                날짜
0              비스포크 인기에 에어컨 생산 풀가동 나선 삼성    매일경제  2022.05.17 10:44
1     비스포크 무풍에어컨 인기…삼성전자 생산라인 2월부터 ‘풀가동’    이데일리  2022.05.17 09:51
2     삼성전자 에어컨 생산라인 풀가동 중…'무풍에어컨 갤러리 효과'   아시아경제  2022.05.17 09:07
3       여름 대목에 대비…삼성전자 2월부터 에어컨 공장 ‘풀가동’   헤럴드경제  2022.05.17 08:58
4         비스포크 무풍 갤러리 인기…삼성 에어컨 생산라인 풀가동   머니투데이  2022.05.17 08:43
..                                   ...     ...               ...
85   삼성전자, 유럽 최대 디스플레이 전시회서 ‘최고의 신기술’ 선정    서울경제  2022.05.15 09:35
86      삼성전자의 '스마트 사이니지' 유럽 최대 전시회 사로잡았다   머니투데이  2022.05.15 09:26
87           삼성전자 제작 단편영화, 5년 만에 日 전국 개봉    서울경제  2022.05.15 14:59
88  유럽 홀린 삼성 스마트 사이니지…ISE 2022서 다수 부문 수상  이코노미스트  2022.05.15 16:01
89      삼성 스마트 사이니지, ISE2022서 최고의 기술력 과시   아시아경제  2022.05.15 10:43

[90 rows x 3 columns]

## 파일로 저장하기

<img src="https://pandas.pydata.org/docs/_images/02_io_readwrite.svg">

In [85]:
file_name = f"news_{item_code}_{item_name}.csv"
file_name

'news_005930_삼성전자.csv'

In [86]:
# to_csv
df_news.to_csv(file_name,encoding='utf-8')

In [92]:
# read_csv
pd.read_csv(file_name).iloc[:,1:]

                                      제목    정보제공                날짜
0              비스포크 인기에 에어컨 생산 풀가동 나선 삼성    매일경제  2022.05.17 10:44
1     비스포크 무풍에어컨 인기…삼성전자 생산라인 2월부터 ‘풀가동’    이데일리  2022.05.17 09:51
2     삼성전자 에어컨 생산라인 풀가동 중…'무풍에어컨 갤러리 효과'   아시아경제  2022.05.17 09:07
3       여름 대목에 대비…삼성전자 2월부터 에어컨 공장 ‘풀가동’   헤럴드경제  2022.05.17 08:58
4         비스포크 무풍 갤러리 인기…삼성 에어컨 생산라인 풀가동   머니투데이  2022.05.17 08:43
..                                   ...     ...               ...
85   삼성전자, 유럽 최대 디스플레이 전시회서 ‘최고의 신기술’ 선정    서울경제  2022.05.15 09:35
86      삼성전자의 '스마트 사이니지' 유럽 최대 전시회 사로잡았다   머니투데이  2022.05.15 09:26
87           삼성전자 제작 단편영화, 5년 만에 日 전국 개봉    서울경제  2022.05.15 14:59
88  유럽 홀린 삼성 스마트 사이니지…ISE 2022서 다수 부문 수상  이코노미스트  2022.05.15 16:01
89      삼성 스마트 사이니지, ISE2022서 최고의 기술력 과시   아시아경제  2022.05.15 10:43

[90 rows x 3 columns]